using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FFPRSaveEditor.SaveFiles
{
    public enum SaveSlot
    {
        Unknown = 0,
        Slot1 = 1,
        Slot2 = 2,
        Slot3 = 3,
        Slot4 = 4,
        Slot5 = 5,
        Slot6 = 6,
        Slot7 = 7,
        Slot8 = 8,
        Slot9 = 9,
        Slot10 = 10,
        Slot11 = 11,
        Slot12 = 12,
        Slot13 = 13,
        Slot14 = 14,
        Slot15 = 15,
        Slot16 = 16,
        Slot17 = 17,
        Slot18 = 18,
        Slot19 = 19,
        Slot20 = 20,
        AutoSave = 21,
        QuickSave = 22,
    }

    public enum FF1CharacterJob
    {
        Unknown = 0,
        Fighter = 1,
        BlackBelt = 2,
        Thief = 3,
        RedMage = 4,
        WhiteMage = 5,
        BlackMage = 6,
        Knight = 7,
        Master = 8,
        Ninja = 9,
        RedWizard = 10,
        WhiteWizard = 11,
        BlackWizard = 12,
    }

    public enum FF1EquipmentSlot
    {
        Unknown = 0,
        Weapon = 1,
        Shield = 2,
        Body = 3,
        Helm = 4,
        Arms = 5,
    }

    public enum FF1ItemType
    {
        Unknown = 0,
        Potion = 2,
        HighPotion = 3,
        XPotion = 4,
        Ether = 5,
        DryEther = 7,
        Elixir = 8,
        PhoenixDown = 10,
        Antidote = 11,
        EyeDrops = 12,
        EchoGrass = 13,
        GoldNeedle = 14,
        Remedy = 15,
        SleepingBag = 17,
        Tent = 18,
        Cottage = 19,
        Lute = 45,
        Crown = 46,
        MysticKey = 49,
        EarthRod = 54,
        Levistone = 55,
        Chime = 56,
        WarpCube = 58,
        Oxyale = 60,
        Canoe = 61,
        Wyrmkiller = 76,
        CoralSword = 77,
        GreatSword = 79,
        Razer = 80,
        MythrilSword = 81,
        VorpalSword = 82,
        FlameSword = 83,
        IceBrand = 86,
        Defender = 87,
        SunBlade = 89,
        Excalibur = 92,
        SasukesBlade = 100,
        Masamune = 103,
        MythrilAxe = 109,
        LightAxe = 110,
        ThorsHammer = 116,
        Staff = 118,
        HealingStaff = 119,
        MagesStaff = 121,
        WizardsStaff = 123,
        MythrilMail = 147,
        Clothes = 134,
        WhiteRove = 136,
        BlackRobe = 137,
        IronArmor = 148,
        IceArmor = 149,
        FlameMail = 150,
        DiamondArmor = 153,
        DragonMail = 154,
        RubyArmlet = 158,
        DiamondArmlet = 160,
        Buckler = 162,
        IronShield = 163,
        MythrilShield = 164,
        IceShield = 165,
        FlameShield = 166,
        DiamondShield = 168,
        AegisShield = 170,
        ProtectCloak = 173,
        LeatherCap = 175,
        Ribbon = 183,
        HealingHelm = 186,
        MythrilHelm = 187,
        DiamondHelm = 188,
        LeatherGloves = 191,
        StellGloves = 193,
        Gauntlets = 194,
        GiantsGloves = 195,
        MythrilGloves = 197,
        DiamondGloves = 198,
        ProtectRing = 202,
    }
}
